library(shiny)
library(chromoMap)
library(shinydashboard)
library(AnnotationDbi)
library(org.Mm.eg.db) #Mus musculus
library(org.Hs.eg.db) #Homo sapiens
#library(org.Dr.eg.db) #Danio rerio (zebra fish)
library(org.Rn.eg.db) #Ratus norvegicus
#library(org.Mmu.eg.db) #Macaca mulata
library(EnsDb.Mmusculus.v79)
library(EnsDb.Hsapiens.v86)
library(EnsDb.Rnorvegicus.v79)
library(limma)
library(tidyverse)
library(DT)
library(RColorBrewer)
library(purrr)
library(plotly)
library(ggpubr)
library(chorddiag)
library(DESeq2)
library(fgsea)
library(shinyalert)
library(shinyBS)
library(shinyWidgets)
library(shinydashboardPlus)
library(pheatmap)
library(shinyjs)
library(shinythemes)
library(rgl)
library(rglwidget)
library(scales)
library(stringr)
library(chromoMap)
source("../utils.R")
# Define UI for application that draws chromoMap


### HEADER ############ 
header <- dashboardHeader(title = "RNAseq viewer and report App", 
                          titleWidth = 300, 
                          dropdownMenuOutput("messageMenu"),
                          tags$li(class = "dropdown", actionButton("aboutButton", "About"),
                                  style="margin-top:8px; margin-right: 5px")
)
### SIDEBAR ##########
sidebar <- dashboardSidebar(useShinyalert(),
                            useShinyjs(),
                            sidebarMenu(
                                menuItem(
                                    pickerInput(
                                        inputId = "specie",
                                        label = "Select specie",
                                        choices = list( "Human" = "Hs", "Mouse" = "Mm", "Ratus" = "Rn"),
                                        options = list(title = "specie"),
                                        selected = NULL
                                    ) 
                                )
                            ),
                            sidebarMenu(
                              menuItem(
                                  uiOutput("deseqFile")
                                )),
                            sidebarMenu(id="menupreview",
                              menuItem("App Information",
                                       tabName = "info",
                                       icon = icon("info")),
                              menuItem("Preview dataset",
                                       tabName = "preview",
                                       icon = icon("eye"))
                              ),
                            sidebarMenu("", sidebarMenuOutput("menu")),
                             sidebarMenu(
                                menuItem(
                                  textInput("author", value="your name...", label = h4("Author report name")
                                  ))),
                              sidebarMenu( 
                                menuItem(
                                  fluidRow(column(12, align = "center", offset=0, uiOutput("report"))))),
                              sidebarMenu(
                                menuItem(
                                  fluidRow(column(12, align = "center", offset=0, uiOutput("pdf")))))
                            )

### BODY ###############
body <- dashboardBody(
     tags$head(
       tags$link(rel = "stylesheet", type = "text/css", href = "customDark.css")
     ),
    setShadow(class = "shiny-plot-output"),
    setShadow( class = "box"),
    setShadow( class = "svg-container"),
    shiny::tagList(shiny::tags$head(
        shiny::tags$link(rel = "stylesheet", type = "text/css", href = "busystyle.css"),
        shiny::tags$script(type = "text/javascript", src = "busy.js")
    )),
    div(
        class = "busy",
        #h4("Loading data, please be patient..."),
        img(src = "dna-svg-small-13.gif", style = "width: 150px"),
        style = "z-index: 99"
    ), 
  bsAlert("alert"),
  tabItems(
    # Initial INFO
    tabItem(tabName = "info",
            chromoMapOutput("ChromoMap"),
            br(),
            fluidRow(column(offset = 2,width = 9,
            box(width=10,
                status = "info",
                title = h1(strong("Welcome to Enrich app 2020!") ),
            h3("Before starting using the app"),
            p("As a necessary initial element to start the analysis, 
                the program imports an object of the type DeseqDataSet, 
                generated by the DESeq function of the", 
              a("DESeq2", href="https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html"),
              "library. It has to be compress as an RDS object and upload 
                by clicking on the search engine button found in the upper left 
                corner of the app. Choose your object and enjoy your enrichment analysis ;)"),
            br(),
            h3("Get the app ready to use!"),
            p("First of all, select the specie of your experiment. 
              Then the option to enter your RDS object containing your 
              analysis will be unlocked. Upload it and wait for the loading 
              to be completed. When the loading symbol stops moving, 
              you can proceed to the next tab! "
              ),
            br(),
            p("Take advantage of every symbol of info" , icon("info-circle"), "that you might find.
              It can provide you with information that may be useful for 
              the proper functioning of the app. "
            ),
            br(),
            h3("How to download the app"),
            p("This app can be found on ",
              a("GitHub.", 
                href = "https://github.com/"))),
    ) ))#,
    # preview tab
    # tabItem(tabName = "preview",
    #         source(file = "../ui-preview-tab.R",
    #         local=TRUE,
    #         encoding = "UTF-8"
    #         )$value),
    # kegg tab content
    # tabItem(tabName = "kegg",
    #         source(file = "../ui-kegg-tab.R",
    #                local = TRUE,
    #                encoding = "UTF-8"
    #                )$value),
    # GO tab GO tab
    # tabItem( tabName = "go",
    #          source(file = "../ui-go-tab.R",
    #                 local = TRUE,
    #                 encoding = "UTF-8",
    #                 )$value),
    # # GSEA tab
    # tabItem( tabName = "gsea",
    #          source(file = "../ui-gsea-tab.R",
    #                 local = TRUE,
    #                 encoding = "UTF-8",
    #                 )$value)
  ) # fin tab items
)# fin dashboardbody

## dflsfd ##################################################
ui <- dashboardPage(title="Rnaseq viewer and report",
                    header,
                    sidebar,
                    body
) # fin del UI

# Define server logic required to draw chromoMap
server <- function(input, output, session) {
   
   output$ChromoMap <- renderChromoMap({
     chromoMap("~/Descargas/chromosome_file.txt","~/Descargas/mini_annotation_file.txt")
   })
}

# Run the application 
shinyApp(ui = ui, server = server)