library(shinydashboard)
library(AnnotationDbi)
library(org.Mm.eg.db) #Mus musculus
library(org.Hs.eg.db) #Homo sapiens
#library(org.Dr.eg.db) #Danio rerio (zebra fish)
library(org.Rn.eg.db) #Ratus norvegicus
#library(org.Mmu.eg.db) #Macaca mulata
library(chorddiag)
library(EnsDb.Mmusculus.v79)
library(EnsDb.Hsapiens.v86)
library(EnsDb.Rnorvegicus.v79)
library(limma)
library(tidyverse)
library(DT)
library(RColorBrewer)
library(purrr)
library(plotly)
library(ggpubr)
library(DESeq2)
library(fgsea)
library(shinyalert)
library(shinyBS)
library(shinyWidgets)
library(shinydashboardPlus)
library(pheatmap)
library(shinyjs)
library(shinythemes)
library(rgl)
library(rglwidget)
library(scales)
library(stringr)
library(shinybusy)
source("utils.R")
options(shiny.maxRequestSize = 3000*1024^2)

### HEADER ############ 
header <- dashboardHeader(title = "RNAseq viewer and report App", 
                          titleWidth = 300, 
                          dropdownMenuOutput("messageMenu"),
                          tags$li(class = "dropdown", actionButton("aboutButton", "About"),
                                  style="margin-top:8px; margin-right: 5px")
)
### SIDEBAR ##########
sidebar <- dashboardSidebar(useShinyalert(),
                            useShinyjs(),
                            sidebarMenu(
                                menuItem(
                                    pickerInput(
                                        inputId = "specie",
                                        label = "Select specie",
                                        choices = list( "Human" = "Hs", "Mouse" = "Mm", "Ratus" = "Rn"),
                                        options = list(title = "specie"),
                                        selected = NULL
                                    ) 
                                )
                            ),
                            sidebarMenu(menuItem(uiOutput("deseqFile"))),
                            sidebarMenu(menuItem(uiOutput("design"))),
                            sidebarMenu(id="menupreview",
                              menuItem("App Information",
                                       tabName = "info",
                                       icon = icon("info")),
                              menuItem("Preview dataset",
                                       tabName = "preview",
                                       icon = icon("eye"))
                              ),
                            sidebarMenu("", sidebarMenuOutput("menu")),
                             sidebarMenu(
                                menuItem(
                                  textInput("author", value="your name...", label = h4("Author report name")
                                  ))),
                              sidebarMenu( 
                                menuItem(
                                  fluidRow(column(12, align = "center", offset=0, uiOutput("report"))))),
                              sidebarMenu(
                                menuItem(
                                  fluidRow(column(12, align = "center", offset=0, uiOutput("pdf")))))
                            )

### BODY ###############
body <- dashboardBody(
      add_busy_gif(src="dna-mini.gif", position = "full-page", width = 10, height = 10 ),
     tags$head(
       tags$link(rel = "stylesheet", type = "text/css", href = "customDark.css")
     ),
    setShadow(class = "shiny-plot-output"),
    setShadow( class = "box"),
    setShadow( class = "svg-container"),
    # shiny::tagList(shiny::tags$head(
    #     shiny::tags$link(rel = "stylesheet", type = "text/css", href = "busystyle.css"),
    #     shiny::tags$script(type = "text/javascript", src = "busy.js"))),
    # div( class = "busy",
    #     #h4("Loading data, please be patient..."),
    #     img(src = "dna-svg-small-13.gif", style = "width: 150px"),
    #     style = "z-index: 99"
    # ), 
  bsAlert("alert"),
  tabItems(
    # Initial INFO
    tabItem(tabName = "info",
            br(),
            fluidRow(column(offset = 2,width = 9,
            box(width=10,
                status = "info",
                title = h1(strong("Welcome to Enrich app 2020!") ),
            h3("Before starting using the app"),
            p("As a necessary initial element to start the analysis, 
                the program imports an object of the type DeseqDataSet, 
                generated by the DESeq function of the", 
              a("DESeq2", href="https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html"),
              "library. It has to be compress as an RDS object and upload 
                by clicking on the search engine button found in the upper left 
                corner of the app. Choose your object and enjoy your enrichment analysis ;)"),
            br(),
            h3("Get the app ready to use!"),
            p("First of all, select the specie of your experiment. 
              Then the option to enter your RDS object containing your 
              analysis will be unlocked. Upload it and wait for the loading 
              to be completed. When the loading symbol stops moving, 
              you can proceed to the next tab! "
              ),
            br(),
            p("Take advantage of every symbol of info" , icon("info-circle"), "that you might find.
              It can provide you with information that may be useful for 
              the proper functioning of the app. "
            ),
            br(),
            h3("How to download the app"),
            p("This app can be found on ",
              a("GitHub.", 
                href = "https://github.com/"))),
    ) )),
    # preview tab
    tabItem(tabName = "preview",
            source(file = "ui-preview-tab.R",
            local=TRUE,
            encoding = "UTF-8"
            )$value),
    # kegg tab content
    tabItem(tabName = "kegg",
            source(file = "ui-kegg-tab.R",
                   local = TRUE,
                   encoding = "UTF-8"
                   )$value),
    # GO tab GO tab
    tabItem( tabName = "go",
             source(file = "ui-go-tab.R",
                    local = TRUE,
                    encoding = "UTF-8",
                    )$value),
    # GSEA tab
    tabItem( tabName = "gsea",
             source(file = "ui-gsea-tab.R",
                    local = TRUE,
                    encoding = "UTF-8",
                    )$value)
  ) # fin tab items
)# fin dashboardbody

########################################## UI #################################################

ui <- dashboardPage(title="Rnaseq viewer and report",
                    header,
                    sidebar,
                    body
) # fin del UI

########################################## SERVER #################################################
server <- function(input, output, session) {
  
  observeEvent(input$aboutButton, {
    shinyalert("Enrich app 2020", "Authors:
            Miriam Riquelme Pérez (corresponding author)
            Fernando Pérez Sanz
            For any suggestion or bug, please contact us
            miriam.riquelmep@gmail.com",
               imageUrl = "dna-svg-small-13.gif", 
               imageWidth = 200, imageHeight = 100)})

# Definir reactiveVariables globales ##############
  data <- reactiveValues() # genes
  goDT <- reactiveValues() #pretabla GO
  kgg <- reactiveValues() # enrich kegg
  go <- reactiveValues() # enrich GO
  kggDT <- reactiveValues() # pretabla kegg
  datos <- reactiveValues(dds=NULL) #objetos dds post DESeq()
  gsea <- reactiveValues() # objeto GSEA
  logfcRange <- reactiveValues() # min y max logfc
  res <- reactiveValues()
  vsd <- reactiveValues()
  rlog <- reactiveValues()
  coloresPCA <- reactiveValues(niveles=NULL, numNiveles=NULL)
  numgenesDE <- reactiveValues(up=NULL, down=NULL)
  
  observeEvent(input$deseqFile, {
      datos$dds <- readRDS(input$deseqFile$datapath)
  })
  
  observeEvent(datos$dds,{
        validate(need(datos$dds, ""))
          if(!is(datos$dds, "DESeqDataSet") | !("results" %in% mcols(mcols(datos$dds))$type) ){
          createAlert(session, "alert", "fileAlert",title = "Oops!!", 
          content = "File must be a DESeqDataSet class object
           and you should have run DESeq()", append=FALSE, style = "error")}
  })
  coloresPCA$colores <- reactive({
        tmp = NULL
      for(i in seq_len(coloresPCA$numNiveles)){
          tmp <- c(tmp, input[[ coloresPCA$niveles[i] ]] )
      }
      return(tmp)
  })

  # Acciones al cargar fichero deseq ##########################
  observeEvent(design(), {
    validate(need(design(), ""))
        closeAlert(session, "alert")
          colData(datos$dds)@listData <-
              colData(datos$dds)@listData %>%
              as.data.frame() %>% mutate_at(vars(-sizeFactor,-replaceable), as.character) %>%
              mutate_at(vars(-sizeFactor,-replaceable), as.factor) %>% as.list()
        res$sh <- as.data.frame(lfcShrink(datos$dds, coef=(as.numeric(design())+1), type="apeglm"))
        res$sh <- res$sh[!is.na(res$sh$padj),]
        conversion <- geneIdConverter(rownames(res$sh), specie() )
        res$sh$baseMean <- round(res$sh$baseMean,4)
        res$sh$lfcSE <- round(res$sh$lfcSE,4)
        res$sh$log2FoldChange <- round(res$sh$log2FoldChange,4)
        res$sh <- cbind(`Description`=conversion$description, res$sh)
        res$sh <- cbind(`GeneName_Symbol`=conversion$consensus, res$sh)
        res$sh <-  res$sh %>% select(-c(pvalue))
        if(specie() == "Mm" ){spc = "Mus_musculus"}
        else {spc = "Homo_sapiens"}
        links = paste0("<a href='http://www.ensembl.org/",spc,"/Gene/Summary?db=core;g=",
                       rownames(res$sh),"' target='_blank'>",rownames(res$sh),"</a>")
        res$sh <- cbind(`GeneName_Ensembl`= links, res$sh)
        vsd$data <- vst(datos$dds)
        rlog$datos <- rlog(datos$dds)
        logfcRange$min <- min(res$sh$log2FoldChange)
        logfcRange$max <- max(res$sh$log2FoldChange)
        closeAlert(session, "fileAlert")
      
  })
  # Acciones al pulsar el boton enrich #####################
  observeEvent(input$runEnrich, {
    data$genesUp <- getSigUpregulated(res$sh, padj(), logfc()[2], specie() ) 
    data$genesDown <- getSigDownregulated(res$sh, padj(), logfc()[1], specie() ) 
    data$genesall <- rbind(data$genesUp, data$genesDown)
    
    kgg$all <- customKegg(data$genesall, species = specie() ) #"Mm"), species.KEGG = "mmu")
    kggDT$all <- kegg2DT(kgg$all, data$genesall)
    
    kgg$up <- customKegg(data$genesUp, species = specie() )#"Mm")#, species.KEGG = "mmu")
    kggDT$up <- kegg2DT(kgg$up, data$genesUp)
    
    kgg$down <- customKegg(data$genesDown, species = specie() )# "Mm")#, species.KEGG = "mmu")
    kggDT$down <- kegg2DT(kgg$down, data$genesDown)
    
    go$all <- customGO(data$genesall, species = "Mm")
    goDT$all <- go2DT(enrichdf = go$all, data = data$genesall )
    
    go$up <- customGO(data$genesUp, species = "Mm")
    goDT$up <- go2DT(enrichdf = go$up, data = data$genesUp )
    
    go$down <- customGO(data$genesDown, species = "Mm")
    goDT$down <- go2DT(enrichdf = go$down, data = data$genesDown )
    updateTabItems(session, "menupreview", "preview")
  })
  # Acciones al seleccionar variables ################
  observeEvent(input$variables, {
        if(!is.factor(colData(datos$dds)[[ variables()[1] ]] ) ){
          coloresPCA$niveles <- as.character(unique( colData(datos$dds)[[ variables()[1] ]] ))
      } else {
          coloresPCA$niveles <- as.character(levels(colData(datos$dds)[[ variables()[1] ]]))
      }
      coloresPCA$numNiveles <- length(coloresPCA$niveles)
  })
  
  # generate reactive variable ###################
  rowsAll <- reactive({input$tableAll_rows_selected})
  rowsUp <- reactive({input$table_rows_selected})
  rowsdown <- reactive({input$tableDown_rows_selected})
  
  bprowsall <- reactive({input$tableBPall_rows_selected}) 
  mfrowsall <- reactive({input$tableMFall_rows_selected})
  ccrowsall <- reactive({input$tableCCall_rows_selected})
  
  bprowsup <- reactive({input$tableBP_rows_selected})
  mfrowsup <- reactive({input$tableMF_rows_selected})
  ccrowsup <- reactive({input$tableCC_rows_selected})
  
  bprowsdown <- reactive({input$tableBPdown_rows_selected})
  mfrowsdown <- reactive({input$tableMFdown_rows_selected})
  ccrowsdown <- reactive({input$tableCCdown_rows_selected})
  
  variables <- reactive({input$variables})
  samplename <- reactive({input$samplename})
  gsearow <- reactive({input$gseaTable_rows_selected})
  specie <- reactive({input$specie})
  padj <- reactive({input$padj})
  logfc <- reactive({input$logfc})
  specie <- reactive({input$specie})
  biologicalText <- reactive({input$biologicalText})
  explainPreview <- reactive({input$explainPreview})
  keggAllText <- reactive({input$keggAllText})
  GSEAText <- reactive({input$GSEAText})
  specie <- reactive({input$specie})
  numheatmap <- reactive({input$numheatmap})
  gene <- reactive({input$gene})
  typeBarKeggAll <- reactive({input$selectkeggall})
  typeBarBpAll <- reactive({input$selectbpall})
  typeBarMfAll <- reactive({input$selectmfall})
  typeBarCcAll <- reactive({input$selectccall})
  pca3d <- reactive({input$pca3d})
  boxplotswitch <- reactive({input$boxplotswitch})
  design <- reactive({input$designPicker})
  # InputFile #################
  output$deseqFile <- renderUI({
      validate(need(specie(), ""))
      fileInput("deseqFile",
          "Choose RDS with DESeq object",
          placeholder = "RDS DESeq",
          accept = ".Rds")
  })
  # InputDesign ###########################
  output$design <- renderUI({
        validate(need(datos$dds,""))
          opciones <- as.list(seq_len(length(resultsNames(datos$dds)[-1] )))
          names(opciones) <- resultsNames(datos$dds)[-1]
          pickerInput(
          inputId = "designPicker",
          label = "Select design",
          choices = opciones,
          options = list(title = "Design"),
          selected = NULL
        ) 
          })
  # side bar menu ####################
  output$menu <- renderMenu({
      validate(need(kgg$all, ""))
      sidebarMenu(
          menuItem(
              "Kegg Enrichment",
              tabName = "kegg",
              icon = icon("chart-bar")
          ),
          menuItem(
              "GO Enrichment",
              tabName = "go",
              icon = icon("chart-bar")
          ),
          menuItem("GSEA",
                   tabName = "gsea",
                   icon = icon("chart-line"))
      )
      })
  # ui selector sample groups ###################
  output$sampleGroup <- renderUI({
    validate(need(datos$dds, ""))
    nvars <- colData(datos$dds) %>% 
      as.data.frame() %>% 
      select(-c(sizeFactor,replaceable)) %>% 
      names()
    selectInput("variables", label="Select condition[s] of interest to highlight",
                choices = nvars,
                multiple = TRUE)
  })
  
  # ui selector sample name ###################
  output$samplesName <- renderUI({
    validate(need(datos$dds, ""))
    nvars <- colData(datos$dds) %>% 
      as.data.frame() %>% 
      select(-c(sizeFactor,replaceable)) %>% 
      names()
    selectInput("samplename", label="Select column to use for sample name",
                choices = nvars,
                multiple = FALSE)
  })
  
  # ui selector logfc #######################
  output$logfc <- renderUI({
    validate(need(datos$dds, ""))
    sliderInput("logfc", label = "Select logFC range to remove (keeps the tails)",
                min=round(logfcRange$min,3), max=round(logfcRange$max, 3),
                #value = c(round(logfcRange$min,3)+1,round(logfcRange$max,3)-1 ), step = 0.1 )
                value = c(-0.5,0.5), step = 0.1 )
  })
  
  # ui selector padj #################################
  output$padj <- renderUI({
    validate(need(datos$dds,""))
    sliderInput("padj", label = "Select p-adjusted threshold (corrected p-value)", min = 0, max=0.2, value=0.05, step = 0.005 )
  })
  # ui selector Colores para PCA y demás #######################
  output$colorPalettes <- renderUI({
      validate(need(datos$dds, ""))
      validate(need(variables(), ""))
      validate(need(coloresPCA$numNiveles, ""))
      l1 <- rep(1:6, times = coloresPCA$numNiveles / 6 , length.out = coloresPCA$numNiveles)
      l2 <- rep(1:9, each = 6, length.out = coloresPCA$numNiveles)
      selectores <- lapply(seq_len(coloresPCA$numNiveles), function(x){
          spectrumInput(
            inputId = paste0(coloresPCA$niveles[x]),
            label = paste0("Select ",coloresPCA$niveles[x]," color"),
            selected = choices_brewer2[[l1[x]]][l2[x]],
            choices = choices_brewer2,
            width = "50%",
            options = list(`toggle-palette-more-text` = "Show more")
            )
      })
  })
 
  # infoboxes ###############################
  output$allbox <- renderInfoBox({
      validate(need(res$sh, ""))
      validate(need(padj(), ""))
      validate(need(logfc(), ""))
      numall <- nrow( res$sh[ ((res$sh$log2FoldChange >= logfc()[2] |
                                    res$sh$log2FoldChange< logfc()[1]) &
                                   res$sh$padj <= padj() ),] ) 
      infoBox("All DE genes", numall, icon = icon("arrows-alt-v"), color = "light-blue", fill = TRUE)
  })
  output$upbox <- renderInfoBox({
      validate(need(res$sh, ""))
      validate(need(padj(), ""))
      validate(need(logfc(), ""))
      numup <- nrow( res$sh[(res$sh$log2FoldChange >= logfc()[2]) & (res$sh$padj <= padj()), ]) 
      numgenesDE$up <- numup
      infoBox("Upregulated genes", numup, icon = icon("thumbs-up", lib = "glyphicon"), color = "light-blue", fill=TRUE)
  })
  output$downbox <- renderInfoBox({
      validate(need(res$sh, ""))
      validate(need(padj(), ""))
      validate(need(logfc(), ""))
      numdown <- nrow( res$sh[(res$sh$log2FoldChange <= logfc()[1]) & (res$sh$padj <= padj()), ])
      numgenesDE$down <- numdown
      infoBox("Downregulated genes", numdown, icon = icon("thumbs-down", lib = "glyphicon"), color = "light-blue", fill=TRUE)
  })
  
  output$fcdown <- renderUI({
        validate(need(logfcRange$min, ""))
        validate(need(logfc(),""))
        initMin <- round( logfcRange$min, 2)
        initMax <- round( logfcRange$max, 2)
        if(logfc()[1]>=0){
            fgColor="#6baed6"
            inputColor="white"
            bgColor ="#46505a"
            rotation="clockwise"
            min=0
            max=initMax
            angleOffset = 0
        }else{
            fgColor="#46505a"
            inputColor="white"
            bgColor ="#e6550d"
            rotation="clockwise"
            min=initMin
            max=0
            angleOffset=180
        }
      knobInput(
          inputId = "myKnobdown",
          label = "Lower logFC cutoff",
          value = round(logfc()[1],2),
          min = min,
          max=max,
          rotation=rotation,
          displayPrevious = TRUE,
          fgColor = fgColor,
          inputColor = inputColor,
          bgColor = bgColor,
          #angleArc = 180,
          #angleOffset = angleOffset,
          width = "80%",
          height = "80%"
      )
  })
  output$fcup <- renderUI({
        validate(need(logfcRange$min, ""))
        validate(need(logfc(),""))
        initMin <- round( logfcRange$min, 2)
        initMax <- round( logfcRange$max, 2)
        if(logfc()[2]>=0){
            fgColor="#6baed6"
            inputColor="white"
            bgColor ="#46505a" 
            rotation="clockwise"
            min=0
            max=initMax
            angleOffset = 0
        }else{
            fgColor="#46505a"
            inputColor="white"
            bgColor ="#e6550d"
            rotation="clockwise"
            min=initMin
            max=0
            angleOffset=180
        }
      knobInput(
          inputId = "myKnobup",
          label = "Upper LogFC cutoff",
          value = round(logfc()[2], 2),
          min = min,
          max=max,
          rotation=rotation,
          displayPrevious = TRUE,
          fgColor = fgColor,
          inputColor = inputColor,
          bgColor = bgColor,
          #angleArc = 180,
          #angleOffset = angleOffset,
          width = "80%",
          height = "80%"
      )
  })
  output$pval <- renderUI({
      validate(need(padj(), ""))
      fgColor = "#74c476"
      inputColor = "white"
      bgColor = "#46505a"
      knobInput(
          inputId = "myKnobpval",
          label = "P.adj cutoff",
          value = round(padj(), 2),
          min = 0,
          max = 0.2,
          rotation = "clockwise",
          displayPrevious = TRUE,
          fgColor = fgColor,
          inputColor = inputColor,
          bgColor = bgColor,
          #angleArc = 180,
          #angleOffset = 90,
          width = "80%",
          height = "80%"
      )
  })

  # preview samples ###################
  output$samples <- DT::renderDataTable(server = TRUE,{
    validate(need(datos$dds, "Load file to render table"))
    metadata <- as.data.frame(colData(datos$dds)) %>% select(-c(sizeFactor,replaceable))
    tituloTabla <- paste0("Table: ColData | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel", filename="coldata", title=tituloTabla),
        list(extend = "pdf", filename="coldata", title = tituloTabla),
        list(extend = "print", title=tituloTabla) )
    datatable( metadata, extensions = "Buttons",
               rownames=FALSE,
               filter = list(position="top", clear=FALSE),
               options = list(
                 columnDefs = list(list(orderable = TRUE,
                                        className = "details-control",
                                        targets = 1),
                                   list(className = "dt-right", targets = 1:(ncol(metadata)-1))
                 ),
                 dom = "Bfrtipl",
                 buttons = customButtons,
                 list(pageLength = 10, white_space = "normal")
               )
    )
  })  
  # preview table ###################
  output$preview <- DT::renderDT(server=TRUE,{
    validate(need(datos$dds, "Load file to render table"))
    validate(need(res$sh, "Load file to render table"))
    res.sh <- res$sh
    res.sh <- res.sh[ ((res.sh$log2FoldChange >= logfc()[2] |
                          res.sh$log2FoldChange < logfc()[1]) &
                         res.sh$padj <= padj() ),]
    tituloTabla <- paste0("Table: Expression values | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "expressionValues",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "expressionValues",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable( res.sh, extensions = "Buttons", escape = FALSE,
               rownames = FALSE,
               filter = list(position="top", clear=FALSE),
               options = list(order = list(list(6, 'asc')),
                 lengthMenu = list(c(10,25,50,100,-1), c(10,25,50,100,"All")),
                 columnDefs = list(list(orderable = TRUE,
                                        className = "details-control",
                                        targets = 1),
                                   list(className = "dt-right", targets = 1:(ncol(res.sh)-1))
                 ),
                 rowCallback = JS(
                   "function(row, data) {",
                   "for (i = 6; i < 8; i++) {",
                   "if (data[i]>1000 | data[i]<1){",
                   "$('td:eq('+i+')', row).html(data[i].toExponential(3));",
                   "}",
                   "}",
                   "}"),
                 dom = "Bfrtipl",
                 buttons = customButtons,
                 list(pageLength = 10, white_space = "normal")
               )
    )
  })
  # view pca plot data ###################
output$pca3 <- renderUI({
      if (!isTRUE(pca3d())) {
          plotlyOutput("pca", width = "100%", height = "800px")
      } else{
          rglwidgetOutput("pca3d", width = "500px", height = "500px")
      }
  })

output$pca <- renderPlotly({
    validate(need(!isTRUE(pca3d()), ""))
    validate(need(datos$dds, ""))
    validate(need(variables(), "Select condition to render PCA"))
    validate(need(samplename(), ""))
    validate(need(coloresPCA$colores(), ""))
    plotPCA(
        rlog$datos,
        intgroup = variables(),
        labels = samplename(),
        customColor = coloresPCA$colores()
    ) +
        theme(plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), "cm")) +
        scale_size_manual(values = 3) +
        theme(text = element_text(size = 16))
})

output$pca3d <- renderRglwidget({
    validate(need(datos$dds, ""))
    validate(need(variables(),"Select condition to render PCA" ) )
    validate(need(coloresPCA$colores(), "" ))
    d <- pca3dplot(rlog$datos, intgroup = variables(), ntop = 500,
                   returnData = TRUE )
    levels(d$labels) <- coloresPCA$colores()
    try(rgl.close(), silent = TRUE)
    rgl.open(useNULL = TRUE) 
    x = d$PC1; y = d$PC2; z = d$PC3
    plot3d(x,y,x, size = 2, type="s", col = (d$labels),
           box=FALSE, axes=FALSE, xlab = names(d)[1],
           ylab=names(d)[2], names(d)[3])
    bg3d(sphere = FALSE, fogtype = "none", color = "#46505a")#"#dadee3" )
    #rgl.bbox(xlen=0, ylen=0, zlen=0)
    rgl.lines(c(min(x), max(x)), c(0, 0), c(0, 0), color = "white")
    rgl.lines(c(0, 0), c(min(y),max(y)), c(0, 0), color = "white")
    rgl.lines(c(0, 0), c(0, 0), c(min(z),max(z)), color = "white")
    rglwidget()
  })
  
  # view Volcano plot data ###################
   output$volcano <- renderPlot( {
    #validate(need(datos$dds, "Load file and condition to render Volcano"))
    validate(need(res$sh, "Load file to render plot"))
    res$sh$GeneName_Symbol <- as.character(res$sh$GeneName_Symbol)
    CustomVolcano(res$sh, lab = res$sh$GeneName_Symbol, 
                  x = 'log2FoldChange',
                  y = 'padj',
                  pCutoff = padj(),
                  FCcutoffUP = logfc()[2],
                  FCcutoffDOWN = logfc()[1],
                  xlim = c(-8, 8),
                  col = c("gray", "#7cccc3", "#d99c01", input$upColor, input$downColor)
                  #input$nsColor, input$logfcColor, input$padjColor, input$bothColor)
                  )
  })
  # view MA plot data ###################
  output$MA <- renderPlot( {
    #validate(need(datos$dds, ""))
    validate(need(res$sh, "Load file to render plot"))
    validate(need(logfc(), ""))
    MA(res$sh, main = 'MA plot applying the DESeq2 Shrinkage normalization for Foldchange',
       fdr = padj(), fcDOWN = logfc()[1], fcUP = logfc()[2] , size = 1.5,
       palette = c(input$upColor, input$downColor, "gray"),
       genenames = res$sh$GeneName_Symbol,
       legend = "top", top = 15, select.top.method = c('padj','fc'),
       font.label = c("plain", 12),
       font.legend = c("plain", 15),
       font.main = "plain",
       cex.axis = 1.1, cex.lab = 1.3,
       ggtheme = theme_classic()
    )
  })
  # view HEATMAP data ###################
  output$heat <- renderPlot( {
    validate(need(datos$dds, ""))
    validate(need(vsd$data, "Load file to render plot"))
    validate(need(variables(),"Load condition to render plot" ) )
    validate(need(samplename(),"Load condition to render plot" ) )
    heat(vsd$data, n=numheatmap(), intgroup = variables(), sampleName = samplename(),
         specie=specie(), customColor = coloresPCA$colores() )
  })
  # view CLUSTER data ###################
  output$cluster <- renderPlot( {
    validate(need(datos$dds, ""))
    validate(need(vsd$data, "Load file to render plot"))
    validate(need(variables(),"Load condition to render plot" ) )
    validate(need(samplename(),"Load condition to render plot" ) )
    cluster(vsd$data, intgroup = samplename())
  })
# view TOP6 data ###################
  output$top6 <- renderPlotly( {
    validate(need(datos$dds, ""))
    validate(need(res$sh, "Load file to render plot"))
    validate(need(variables(),"Load condition to render plot" ) )
    validate(need(coloresPCA$colores(), ""))
    topGenes <- rownames(res$sh)[order(res$sh$padj)][1:6]
    topSymbol <- as.character(res$sh$GeneName_Symbol)[order(res$sh$padj)][1:6]
    z <- lapply(topGenes, function(x) plotCounts(dds=datos$dds, gene=x,
                                                 res=res$sh, intgroup = variables(),
                                                 returnData = TRUE))
    z <- lapply(z, function(x){x %>% group_by(!!as.name(variables()[1])) %>%
        mutate(mean = round(mean(count),2), sem = round(sd(count)/sqrt(n()),3 ), n = n() ) %>% 
        mutate(text = paste0("Mean: ",mean,"\n","SEM: ",sem)) } )
    z <- do.call(rbind, z)
    z$symbol <- rep(topSymbol, each =(nrow(z)/6) ) 
    z[[variables()[1]]] <- as.factor(z[[variables()[1]]])
    p <- ggplot(z, aes_(as.name(variables()), ~count, colour = as.name(variables()[1] ), text = ~text ) ) + 
      scale_y_log10() +
      geom_point(position = position_jitter(width = 0.1, height = 0), size = 2) +
      facet_wrap(~symbol) + scale_color_manual( values = coloresPCA$colores() ) +
      ggtitle("Expression of top 6 most significant genes")
    p %>% ggplotly(tooltip = c("x","y","text"))
    })
# view TOP1 data ###################  
  output$top1 <- renderPlotly( {
    validate(need(datos$dds, ""))
    validate(need(res$sh, "Load file to render plot"))
    validate(need(variables(),"Load condition to render plot" ) )
    validate(need(coloresPCA$colores(), ""))
    validate(need(gene(), "Enter a gene of interest in Ensembl or symbol name"))
    gene <- gene()
    if (grepl("^ENS", gene, ignore.case = TRUE)) {
        gene <- toupper(gene)
        z <- plotCounts(dds = datos$dds,gene = gene, returnData = TRUE,
                        intgroup = variables()[1])
        symbol = as.character(res$sh$GeneName_Symbol[rownames(res$sh) == gene])
    } else{
        if (specie() == "Mm" | specie() == "Rn") {
            gene <- stringr::str_to_title(gene)
        }
        else{
            gene = toupper(gene)
        }
        z <- plotCountsSymbol(dds = datos$dds, gene = gene, returnData = TRUE,
                              intgroup = variables()[1], specie=specie())
        symbol <- gene
    }
    z <- z %>% group_by(!!as.name(variables()[1])) %>%
        mutate(mean = round(mean(count),2), sem = round(sd(count)/sqrt(n()),3 ), n = n() ) %>% 
        mutate(text = paste0("Mean: ",mean,"\n","SEM: ",sem))
    p <- z %>% ggplot(aes_(as.name(variables()[1]), ~count, colour = as.name(variables()[1] ),
                           text = ~text) ) + scale_y_log10() +
        geom_point(position = position_jitter(width = 0.1, height = 0), size = 2)+
        scale_color_manual( values = coloresPCA$colores() )+
        ggtitle(paste0(symbol) )
    output$top1text <- renderUI({
        validate(need(gene(), ""))
        texto <- as.data.frame(unique(z[ ,c(variables()[1],"text") ] ))
        txt <- paste0(apply(texto, 1, function(x){x} ), collapse = "<br/><br/>")
        txt <- gsub("\n","<br/>",txt)
        tags$h5(HTML(txt))
    })
    p %>% ggplotly(tooltip = c("x","y","text"))
  })

 # Boxviolin plot #################################
  output$boxviolin <- renderPlotly({
          validate(need(datos$dds, "Load file and condition to render Volcano"))
          validate(need(vsd$data, ""))
          validate(need(variables(), ""))
          validate(need(samplename(),"" ) )
          validate(need(coloresPCA$colores(), ""))
          boxViolin( names = samplename() , vsd=vsd$data, boxplotswitch=boxplotswitch(),
                    intgroup=variables(), customColor = coloresPCA$colores()) 
  })

# KEGG table All #####################################
  output$tableAll <- DT::renderDT(server=TRUE,{
    validate(need(kgg$all, "Load file to render table"))
    names(kggDT$all)[names(kggDT$all) == "DE"] <- "DEG"
    names(kggDT$all)[names(kggDT$all) == "P.DE"] <- "p-value"
    tituloTabla <- paste0("Table: Kegg all genes | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "keggAll",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "keggAll",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(
      kggDT$all, 
      vars = c("genes"),
      filter = list(position="top", clear=FALSE),
      escape = FALSE,
      opts = list(order = list(list(5, 'asc')),
        pageLength = 10, white_space = "normal",
        buttons = customButtons
        ) )
  }) 
# KEGG barplot All ################
  output$keggPlotAll <- renderPlotly ({
    validate(need(kgg$all, "Load file to render BarPlot"))
    rowsAll <- rowsAll()
    if(is.null(rowsAll)){
        if( dim(kgg$all)[1]<10 ){rowsAll <-  seq_len(nrow(kgg$all)) }
        else{ rowsAll <-  seq_len(10)  }
        }
    p <- plotKeggAll(enrichdf = kgg$all[rowsAll,], nrows = length(rowsAll),
                genesUp = data$genesUp, genesDown = data$genesDown,
                colors = c(input$downColor, input$upColor))
    if(typeBarKeggAll() == "Dodge"){
        print(p[[1]])   } else if(typeBarKeggAll()=="Stack"){
            print(p[[2]])} else {print(p[[3]])}
        
  })
  # KEGG chordiag plot All ###############
  output$keggChordAll <- renderChorddiag({
    validate(need(kgg$all, "Load file to render ChordPlot"))
    rowsAll <- rowsAll()
    if(is.null(rowsAll)){
        if( dim(kgg$all)[1]<10 ){rowsAll <-  seq_len(nrow(kgg$all)) }
        else{ rowsAll <-  seq_len(10)  }
        }
    chordPlot(kgg$all[rowsAll, ], nRows = length(rowsAll), orderby = "P.DE")
  })
output$legendChorAll <- renderPlot({
    validate(need(kgg$all, "Load file to render ChordPlot"))
    rowsAll <- rowsAll()
    if(is.null(rowsAll)){
        if( dim(kgg$all)[1]<10 ){rowsAll <-  seq_len(nrow(kgg$all)) }
        else{ rowsAll <-  seq_len(10)  }
        }
    legendChorplot(kgg$all[rowsAll, ] )
  })
  # KEGG dotplot All ################### 
  output$keggDotAll <- renderPlot({
    validate(need(kgg$all, "Load file and select to render dotPlot"))
    validate(need(rowsAll(), "Select the paths of interest to render DotPlot"))
    rowsAll <- rowsAll()
    if(is.null(rowsAll)){rowsAll <- c(1:20)}
    dotPlotkegg(kgg$all[rowsAll,], n = length(rowsAll))
  })
  # KEGG heatmap All #################
  output$heatmapKeggAll <- renderPlot({
    validate(need(kgg$all, "Load file and select to render Heatmap"))
    validate(need(rowsAll(), "Select the paths of interest to render HeatMap"))
    validate(need(kggDT$all, ""))
    heatmapKegg(kggDT$all, rowsAll() ) 
  })
  # KEGG cnet All #################
  output$cnetKeggAll <- renderPlot({
    validate(need(kgg$all, "Load file and select to render Net Plot"))
    validate(need(rowsAll(), "Select the paths of interest to render NetPlot"))
    customCnetKegg(kgg$all, rowsAll())
  })
  # KEGG table up#####################################
  output$table <- DT::renderDT(server=TRUE,{
    validate(need(kgg$up, "Load file to render table"))
    names(kggDT$up)[names(kggDT$up) == "DE"] <- "DEG"
    names(kggDT$up)[names(kggDT$up) == "P.DE"] <- "p-value"
    tituloTabla <- paste0("Table: Kegg up-regulated genes | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "keggUp",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "keggUp",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(
      kggDT$up,
      vars = c("genes"),
      filter = list(position="top", clear=FALSE),
      escape = FALSE,
      opts = list(order = list(list(5, 'asc')),
        pageLength = 10, white_space = "normal",
        buttons = customButtons))
  }) 
  # KEGG barplot up################
  output$keggPlot <- renderPlotly ({
    validate(need(kgg$up, "Load file to render BarPlot"))
    rowsUp <- rowsUp()
    if(is.null(rowsUp)){
        if( dim(kgg$up)[1]<10 ){rowsUp <-  seq_len(nrow(kgg$up)) }
        else{ rowsUp <-  seq_len(10)  }
        }
    plotKegg(enrichdf = kgg$up[rowsUp,], nrows = length(rowsUp), colors = c(input$upColor))
  })
  # KEGG chordiag plot up ###############
  output$keggChord <- renderChorddiag({
    validate(need(kgg$up, "Load file to render ChordPlot"))
    rowsUp<- rowsUp()
    if(is.null(rowsUp)){
        if( dim(kgg$up)[1]<10 ){rowsUp <-  seq_len(nrow(kgg$up)) }
        else{ rowsUp <-  seq_len(10)  }
        }
    chordPlot(kgg$up[rowsUp, ], nRows = length(rowsUp), orderby = "P.DE")
  })
 output$legendChorUp <- renderPlot({
    validate(need(kgg$up, "Load file to render ChordPlot"))
    rowsUp <- rowsUp()
    if(is.null(rowsUp)){
        if (dim(kgg$up)[1] < 10) {rowsUp <-  seq_len(nrow(kgg$up))}
        else{rowsUp <-  seq_len(10)}
        
        }
    legendChorplot(kgg$up[rowsUp, ] )
  })
  # KEGG dotplot UP ################### 
  output$keggDotUp <- renderPlot({
    validate(need(kgg$up, "Load file and select to render dotPlot"))
    validate(need(rowsUp(), "Select the paths of interest to render DotPlot"))
    rowsUp <- rowsUp()
    if(is.null(rowsUp)){rowsUp <- c(1:20)}
    dotPlotkegg(kgg$up[rowsUp,], n = length(rowsUp))
  })
  # KEGG heatmap Up #################
  output$heatmapKeggUp <- renderPlot({
    validate(need(kgg$up, "Load file and select to render Heatmap"))
    validate(need(rowsUp(), "Select the paths of interest to render HeatMap"))
    validate(need(kggDT$up, ""))
    heatmapKegg(kggDT$up, rowsUp())
  })
  # KEGG cnet Up #################
  output$cnetKeggUp <- renderPlot({
    validate(need(kgg$up, "Load file and select to render Net Plot"))
    validate(need(rowsUp(), "Select the paths of interest to render NetPlot"))
    customCnetKegg(kgg$up, rowsUp())
  })
  
  # KEGG table down #####################################
  output$tableDown <- DT::renderDT(server=TRUE,{
    validate(need(kgg$down, "Load file to render table"))
    names(kggDT$down)[names(kggDT$down) == "DE"] <- "DEG"
    names(kggDT$down)[names(kggDT$down) == "P.DE"] <- "p-value"
    tituloTabla <- paste0("Table: Kegg down-regulated genes | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "keggDown",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "keggDown",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(
      kggDT$down,
      vars = c("genes"),
      filter = list(position="top", clear=FALSE),
      escape = FALSE,
      opts = list(order = list(list(5, 'asc')),
        pageLength = 10, white_space = "normal",
        buttons = customButtons))
  }) 
  # KEGG barplot down ################
  output$keggPlotDown <- renderPlotly ({
    validate(need(kgg$down, "Load file to render BarPlot"))
    rowsdown <- rowsdown()
    if(is.null(rowsdown)){
        if( dim(kgg$down)[1]<10 ){rowsdown <-  seq_len(nrow(kgg$down)) }
        else{ rowsdown <-  seq_len(10)  }
        }
    plotKegg(enrichdf = kgg$down[rowsdown,], nrows = length(rowsdown), 
             colors = c(input$downColor))
  })
  # KEGG chordiag plot down ###############
  output$keggChordDown <- renderChorddiag({
    validate(need(kgg$down, "Load file to render ChordPlot"))
    rowsdown <- rowsdown()
    if(is.null(rowsdown)){
        if( dim(kgg$down)[1]<10 ){rowsdown <-  seq_len(nrow(kgg$down)) }
        else{ rowsdown <-  seq_len(10)  }
        }
    chordPlot(kgg$down[rowsdown, ], nRows = length(rowsdown), orderby = "P.DE")
  })
  output$legendChorDown <- renderPlot({
    validate(need(kgg$down, "Load file to render ChordPlot"))
    rowsdown <- rowsdown()
    if(is.null(rowsdown)){
        if( dim(kgg$down)[1]<10 ){rowsdown <-  seq_len(nrow(kgg$down)) }
        else{ rowsdown <-  seq_len(10)  }
        }
    legendChorplot(kgg$down[rowsdown, ] )
  })
  # KEGG dotplot Down ################### 
  output$keggDotDown <- renderPlot({
    validate(need(kgg$down, "Load file to render DotPlot"))
    validate(need(rowsdown(), "Select the paths of interest to render dotPlot"))
    rowsdown <- rowsdown()
    if(is.null(rowsdown)){rowsdown <- c(1:20)}
    dotPlotkegg(kgg$down[rowsdown,], n = length(rowsdown))
  })
  # KEGG heatmap Down #################
  output$heatmapKeggDown <- renderPlot({
    validate(need(kgg$down, "Load file to render Heatmap"))
    validate(need(rowsdown(), "Select the paths of interest to render Heatmap"))
    heatmapKegg(kggDT$down, rowsdown())
  })
  # KEGG cnet Down #################
  output$cnetKeggDown <- renderPlot({
    validate(need(kgg$down, "Load file to render NetPlot"))
    validate(need(rowsdown(), "Select the paths of interest to render NetPlot"))
    rowsdown <- rowsdown()
    customCnetKegg(kgg$down, rowsdown())
  })

  # GO table BP ALL #####################
  output$tableBPall <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$all, "Load file to render table"))
    goDT <- goDT$all 
    names(goDT)[names(goDT) == "DE"] <- "DEG"
    names(goDT)[names(goDT) == "P.DE"] <- "p-value"
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level) 
    tituloTabla <- paste0("Table: GO-BP all genes | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "BPall",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "BPall",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(goDT[goDT$Ont=="BP",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(order = list(list(6, 'asc')),
                 pageLength = 10, white_space = "normal",
                 buttons = customButtons))
  })
  # GO plots BP all #####################
  output$plotBPall <- renderPlotly({
    validate(need(go$all, "Load file to render plot"))
    bprowsall <- bprowsall()
    if(is.null(bprowsall)){bprowsall <- c(1:10)}
    gosBP <- go$all[go$all$Ont=="BP",]
    p <- plotGOAll(enrichdf = gosBP[bprowsall, ], nrows = length(bprowsall), ont="BP", 
              genesUp = data$genesUp, genesDown = data$genesDown,
              colors = c(input$downColor, input$upColor))
    if( typeBarBpAll() == "Dodge") { print(p[[1]]) }
    else if ( typeBarBpAll() == "Stack") { print(p[[2]]) }
    else { print(p[[3]]) }
  })
  # GO BP dotplot all ################### 
  output$BPDotall <- renderPlot({
    validate(need(go$all, "Load file to render dotPlot"))
    validate(need(bprowsall(), "Select the terms of interest to render DotPlot"))
    bprowsall <- bprowsall()
    if(is.null(bprowsall)){bprowsall <- c(1:20)}
    gosBP <- go$all[go$all$Ont=="BP",]
    dotPlotGO(gosBP[bprowsall,], n = length(bprowsall))
  })
  # GO table MF all #####################
  output$tableMFall <- DT::renderDataTable({
    validate(need(goDT$all, "Load file to render table"))
    goDT <- goDT$all
    names(goDT)[names(goDT) == "DE"] <- "DEG"
    names(goDT)[names(goDT) == "P.DE"] <- "p-value"
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level)
    tituloTabla <- paste0("Table: GO-MF all genes | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "MFall",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "MFall",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(goDT[goDT$Ont=="MF",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(order = list(list(6, 'asc')),
                           pageLength = 10, white_space = "normal",
                           buttons = customButtons,
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots MF all  #####################
  output$plotMFall <- renderPlotly({
    validate(need(go$all, "Load file to render plot"))
    mfrowsall <- mfrowsall()
    if(is.null(mfrowsall)){mfrowsall <- c(1:10)}
    gosMF <- go$all[go$all$Ont=="MF",]
    p <- plotGOAll(enrichdf = gosMF[mfrowsall, ], nrows = length(mfrowsall), ont="MF", 
                   genesUp = data$genesUp, genesDown = data$genesDown,
                   colors = c(input$downColor, input$upColor))
    if( typeBarMfAll() == "Dodge") { print(p[[1]]) }
    else if ( typeBarMfAll() == "Stack") { print(p[[2]]) }
    else { print(p[[3]]) }
  })
  # GO MF dotplot all ################### 
  output$MFDotall <- renderPlot({
    validate(need(go$all, "Load file to render dotPlot"))
    validate(need(mfrowsall(), "Select the terms of interest to render DotPlot"))
    mfrowsall <- mfrowsall()
    if(is.null(mfrowsall)){mfrowsall <- c(1:20)}
    gosMF <- go$all[go$all$Ont=="MF",]
    dotPlotGO(gosMF[mfrowsall,], n = length(mfrowsall))
  })
  # GO table CC all #####################
  output$tableCCall <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$all, "Load file to render table"))
    goDT <- goDT$all
    names(goDT)[names(goDT) == "DE"] <- "DEG"
    names(goDT)[names(goDT) == "P.DE"] <- "p-value"
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level)
    tituloTabla <- paste0("Table: GO-CC all genes | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "CCall",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "CCall",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(goDT[goDT$Ont=="CC",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(order = list(list(6, 'asc')),
                           pageLength = 10, white_space = "normal",
                           buttons = customButtons,
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots CC all #####################
  output$plotCCall <- renderPlotly({
    validate(need(go$all, "Load file to render plot"))
    ccrowsall <- ccrowsall()
    if(is.null(ccrowsall)){ccrowsall <- c(1:10)}
    gosCC <- go$all[go$all$Ont=="CC",]
    p <- plotGOAll(enrichdf = gosCC[ccrowsall, ], nrows = length(ccrowsall), ont="CC", 
                   genesUp = data$genesUp, genesDown = data$genesDown,
                   colors = c(input$downColor, input$upColor))
    if( typeBarCcAll() == "Dodge") { print(p[[1]]) }
    else if ( typeBarCcAll() == "Stack") { print(p[[2]]) }
    else { print(p[[3]]) }
  })
  # GO CC dotplot all ################### 
  output$CCDotall <- renderPlot({
    validate(need(go$all, "Load file to render dotPlot"))
    validate(need(ccrowsall(), "Select the terms of interest to render DotPlot"))
    ccrowsall <- ccrowsall()
    if(is.null(ccrowsall)){ccrowsall <- c(1:20)}
    gosCC <- go$all[go$all$Ont=="CC",]
    dotPlotGO(gosCC[ccrowsall,], n = length(ccrowsall))
  })
  
  # GO table BP UP#####################
  output$tableBP <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$up, "Load file to render table"))
    goDT <- goDT$up
    names(goDT)[names(goDT) == "DE"] <- "DEG"
    names(goDT)[names(goDT) == "P.DE"] <- "p-value"
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level)
    tituloTabla <- paste0("Table: GO-BP up-regulated genes | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "BPup",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "BPup",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(goDT[goDT$Ont=="BP",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(order = list(list(6, 'asc')),
                           pageLength = 10, white_space = "normal",
                           buttons = customButtons))
  })
  # GO plots BP UP #####################
  output$plotBP <- renderPlotly({
    validate(need(go$up, "Load file to render plot"))
    bprowsup <- bprowsup()
    if(is.null(bprowsup)){bprowsup <- c(1:10)}
    gosBP <- go$up[go$up$Ont=="BP",]
    plotGO(enrichdf = gosBP[bprowsup, ], nrows = length(bprowsup), ont="BP",
           colors = c(input$upColor) )
  })
  # GO BP dotplot up ################### 
  output$BPDotUp <- renderPlot({
    validate(need(go$up, "Load file to render dotPlot"))
    validate(need(bprowsup(), "Select the terms of interest to render DotPlot"))
    bprowsup <- bprowsup()
    if(is.null(bprowsup)){bprowsup <- c(1:20)}
    gosBP <- go$up[go$up$Ont=="BP",]
    dotPlotGO(gosBP[bprowsup,], n = length(bprowsup))
  })
  # GO table MF UP #####################
  output$tableMF <- DT::renderDataTable({
    validate(need(goDT$up, "Load file to render table"))
    goDT <- goDT$up
    names(goDT)[names(goDT) == "DE"] <- "DEG"
    names(goDT)[names(goDT) == "P.DE"] <- "p-value"
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level)
    tituloTabla <- paste0("Table: GO-MF up-regulated genes | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "MFup",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "MFup",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(goDT[goDT$Ont=="MF",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(order = list(list(6, 'asc')),
                           pageLength = 10, white_space = "normal",
                           buttons = customButtons,
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots MF UP #####################
  output$plotMF <- renderPlotly({
    validate(need(go$up, "Load file to render plot"))
    mfrowsup <- mfrowsup()
    if(is.null(mfrowsup)){mfrowsup <- c(1:10)}
    gosMF <- go$up[go$up$Ont=="MF",]
    plotGO(enrichdf = gosMF[mfrowsup, ], nrows = length(mfrowsup), ont = "MF",
           colors = c(input$upColor) )
  })
  # GO MF dotplot up ################### 
  output$MFDotUp <- renderPlot({
    validate(need(go$up, "Load file to render dotPlot"))
    validate(need(mfrowsup(), "Select the terms of interest to render DotPlot"))
    mfrowsup <- mfrowsup()
    if(is.null(mfrowsup)){mfrowsup <- c(1:20)}
    gosMF <- go$up[go$up$Ont=="MF",]
    dotPlotGO(gosMF[mfrowsup,], n = length(mfrowsup))
  })
  # GO table CC UP #####################
  output$tableCC <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$up, "Load file to render table"))
    goDT <- goDT$up
    names(goDT)[names(goDT) == "DE"] <- "DEG"
    names(goDT)[names(goDT) == "P.DE"] <- "p-value"
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level)
    tituloTabla <- paste0("Table: GO-CC up-regulated genes | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "CCup",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "CCup",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(goDT[goDT$Ont=="CC",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(order = list(list(6, 'asc')),
                           pageLength = 10, white_space = "normal",
                           buttons = customButtons,
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots CC UP #####################
  output$plotCC <- renderPlotly({
    validate(need(go$up, "Load file to render plot"))
    ccrowsup <- ccrowsup()
    if(is.null(ccrowsup)){ccrowsup <- c(1:10)}
    gosCC <- go$up[go$up$Ont=="CC",]
    plotGO(enrichdf = gosCC[ccrowsup,], nrows = length(ccrowsup), ont="CC",
           colors = c(input$upColor))
  })
  # GO CC dotplot up ################### 
  output$CCDotUp <- renderPlot({
    validate(need(go$up, "Load file to render dotPlot"))
    validate(need(ccrowsup(), "Select the terms of interest to render DotPlot"))
    ccrowsup <- ccrowsup()
    if(is.null(ccrowsup)){ccrowsup <- c(1:20)}
    gosCC <- go$up[go$up$Ont=="CC",]
    dotPlotGO(gosCC[ccrowsup,], n = length(ccrowsup))
  })
  # GO table BP DOWN #####################
  output$tableBPdown <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$down, "Load file to render table"))
    goDT <- goDT$down
    names(goDT)[names(goDT) == "DE"] <- "DEG"
    names(goDT)[names(goDT) == "P.DE"] <- "p-value"
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level)
    tituloTabla <- paste0("Table: GO-BP down-regulated genes | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "BPdown",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "BPdown",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(goDT[goDT$Ont=="BP",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(order = list(list(6, 'asc')),
                           buttons = customButtons,
                           pageLength = 10, white_space = "normal")
    )
  })
  # GO plots BP DOWN #####################
  output$plotBPdown <- renderPlotly({
    validate(need(go$down, "Load file to render plot"))
    bprowsdown <- bprowsdown()
    if(is.null(bprowsdown)){bprowsdown <- c(1:10)}
    gosBP <- go$down[go$down$Ont=="BP",]
    plotGO(enrichdf = gosBP[bprowsdown, ], nrows = length(bprowsdown), ont="BP",
           colors = c(input$downColor))
  })
  # GO BP dotplot down ################### 
  output$BPDotDown <- renderPlot({
    validate(need(go$down, "Load file to render dotPlot"))
    validate(need(bprowsdown(), "Select the terms of interest to render DotPlot"))
    bprowsdown <- bprowsdown()
    if(is.null(bprowsdown)){bprowsdown <- c(1:20)}
    gosBP <- go$down[go$down$Ont=="BP",]
    dotPlotGO(gosBP[bprowsdown,], n = length(bprowsdown))
  })
  # GO table MF DOWN #####################
  output$tableMFdown <- DT::renderDataTable({
    validate(need(goDT$down, "Load file to render table"))
    goDT <- goDT$down
    names(goDT)[names(goDT) == "DE"] <- "DEG"
    names(goDT)[names(goDT) == "P.DE"] <- "p-value"
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level)
    tituloTabla <- paste0("Table: GO-MF down-regulated genes | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "MFdown",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "MFdown",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(goDT[goDT$Ont=="MF",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(order = list(list(6, 'asc')),
                           pageLength = 10, white_space = "normal",
                           buttons = customButtons,
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots MF DOWN #####################
  output$plotMFdown <- renderPlotly({
    validate(need(go$down, "Load file to render plot"))
    mfrowsdown <- mfrowsdown()
    if(is.null(mfrowsdown)){mfrowsdown <- c(1:10)}
    gosMF <- go$down[go$down$Ont=="MF",]
    plotGO(enrichdf = gosMF[mfrowsdown, ], nrows = length(mfrowsdown), ont = "MF",
           colors = c(input$downColor) )
  })
  # GO MF dotplot down ################### 
  output$MFDotDown <- renderPlot({
    validate(need(go$down, "Load file to render dotPlot"))
    validate(need(mfrowsdown(), "Select the terms of interest to render DotPlot"))
    mfrowsdown <- mfrowsdown()
    if(is.null(mfrowsdown)){mfrowsdown <- c(1:20)}
    gosMF <- go$down[go$down$Ont=="MF",]
    dotPlotGO(gosMF[mfrowsdown,], n = length(mfrowsdown))
  })
  # GO table CC DOWN #####################
  output$tableCCdown <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$down, "Load file to render table"))
    goDT <- goDT$down
    names(goDT)[names(goDT) == "DE"] <- "DEG"
    names(goDT)[names(goDT) == "P.DE"] <- "p-value"
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level)
    tituloTabla <- paste0("Table: GO-CC down-regulated genes | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "CCdown",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "CCdown",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(goDT[goDT$Ont=="CC",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(order = list(list(6, 'asc')),
                           pageLength = 10, white_space = "normal",
                           buttons = customButtons,
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots CC DOWN #####################
  output$plotCCdown <- renderPlotly({
    validate(need(go$down, "Load file to render plot"))
    ccrowsdown <- ccrowsdown()
    if(is.null(ccrowsdown)){ccrowsdown <- c(1:10)}
    gosCC <- go$down[go$down$Ont=="CC",]
    plotGO(enrichdf = gosCC[ccrowsdown,], nrows = length(ccrowsdown), ont="CC",
           colors = c(input$downColor) )
  })
  # GO CC dotplot down ################### 
  output$CCDotDown <- renderPlot({
    validate(need(go$down, "Load file to render dotPlot"))
    validate(need(ccrowsdown(), "Select the terms of interest to render DotPlot"))
    ccrowsdown <- ccrowsdown()
    if(is.null(ccrowsdown)){ccrowsdown <- c(1:20)}
    gosCC <- go$down[go$down$Ont=="CC",]
    dotPlotGO(gosCC[ccrowsdown,], n = length(ccrowsdown))
  })
  # GSEA table ##########################
  output$gseaTable <- renderDataTable({
    validate(need(datos$dds, "Load file to render table"))
    gsea$gsea <- gseaKegg(res$sh)
    mygsea <- gsea$gsea
    #saveRDS(mygsea, "tmpResources/gsea.Rds")
    table <- mygsea@result[mygsea@result$p.adjust<=0.05 ,2:9] %>% 
      mutate_at(vars(3:7), ~round(., 4))
    tituloTabla <- paste0("Table: GSEA pathway | ","log2FC: ",logfc()[1],"_",logfc()[2]," | ","padj: ",padj()," | ",
                          "Num genes Up/down: ",numgenesDE$up,"/",numgenesDE$down)
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "GSEAkegg",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "GSEAkegg",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    DT::datatable( table,
                   rownames=FALSE,
                   filter = list(position="top", clear=FALSE),
                   options = list(order = list(list(4, 'asc')),
                     lengthMenu = list(c(10,25,50,100,-1), c(10,25,50,100,"All")),
                     columnDefs = list(list(orderable = FALSE,
                                            className = "details-control",
                                            targets = 1)
                     ),
                     dom = "Bfrtipl",
                     buttons = customButtons,
                     list(pageLength = 10, white_space = "normal")
                   )
    )
  })
  # GSEA plot ##########################
  output$gseaPlot <- renderPlot({
    validate(need(gsea$gsea, "Load file to render table"))
    gseanr <- gsearow()
    if(is.null(gseanr)){gseanr <- c(1)}
    enrichplot::gseaplot2(gsea$gsea, geneSetID = gseanr, pvalue_table = TRUE,
                          ES_geom = "line")
  })
  # author name ######################
  author <- reactive({input$author})
  # generate report #############################
  output$report <- renderUI({
    #validate(need(datos$dds, ""))
    downloadButton("report2", "Generate report")
    
  })
  output$pdf <- renderUI({
    #validate(need(datos$dds, ""))
    downloadButton("reportpdf", "Generate pdf report")
  })
  output$report2 <- downloadHandler(
    # For PDF output, change this to "report.pdf"
    filename = "report.html",
    content = function(file) {
      tempReport <- file.path(tempdir(), "flexReport.Rmd")
      file.copy("flexReport.Rmd", tempReport, overwrite = TRUE)
      file.copy("utils.R", file.path(tempdir(),"utils.R"), overwrite = TRUE)
      file.copy("tmpResources/", tempdir(), overwrite = TRUE, recursive = TRUE)
      file.copy("resources/dna-svg-small-13.gif",
                file.path(tempdir(), "tmpResources/dna-svg-small-13.gif"), overwrite = TRUE)
      #do.call(file.remove, list(list.files("tmpResources/", full.names = TRUE)))
      nrall <- rowsAll()
      nrup <- rowsUp()
      nrdown <- rowsdown()
      bpnrup <- bprowsup()
      mfnrup <- mfrowsup()
      ccnrup <- ccrowsup()
      bpnrdown <- bprowsdown()
      mfnrdown <- mfrowsdown()
      ccnrdown <- ccrowsdown()
      variablepca <- variables()
      samplecluster <- samplename()
      gseanr <- gsearow()
      bpnrall <- bprowsall()
      mfnrall <- mfrowsall()
      ccnrall <- ccrowsall()
      if(is.null(gseanr)){gseanr <- c(1)}
      if(is.null(nrup)){ nrup <- ( if( dim(kggDT$up)[1]<10) 1:dim(kggDT$up)[1] else c(1:10) ) } 
      if(is.null(nrall)){ nrall <-  ( if( dim(kggDT$all)[1]<10) 1:dim(kggDT$all)[1] else c(1:10) ) }
      if(is.null(nrdown)){ nrdown <- ( if( dim(kggDT$down)[1]<10) 1:dim(kggDT$down)[1] else c(1:10) ) }
      
      if(is.null(ccnrup)){ ccnrup <- ( if (dim(goDT$up[goDT$up$Ont=="CC", ])[1]<10)
                                             1:dim(goDT$up[goDT$up$Ont=="CC", ])[1] else c(1:10) ) }
      if(is.null(mfnrup)){ mfnrup <- ( if (dim(goDT$up[goDT$up$Ont=="MF", ])[1]<10)
                                             1:dim(goDT$up[goDT$up$Ont=="MF", ])[1] else c(1:10) ) }
      if(is.null(bpnrup)){ bpnrup <- ( if (dim(goDT$up[goDT$up$Ont=="BP", ])[1]<10)
                                             1:dim(goDT$up[goDT$up$Ont=="BP", ])[1] else c(1:10) )}
      
      if(is.null(ccnrdown)){ccnrdown <- ( if (dim(goDT$down[goDT$down$Ont=="CC", ])[1]<10)
                                              1:dim(goDT$down[goDT$down$Ont=="CC", ])[1] else c(1:10) ) }
      if(is.null(mfnrdown)){mfnrdown <- ( if (dim(goDT$down[goDT$down$Ont=="MF", ])[1]<10)
                                              1:dim(goDT$down[goDT$down$Ont=="MF", ])[1] else c(1:10) ) }
      if(is.null(bpnrdown)){bpnrdown <- ( if (dim(goDT$down[goDT$down$Ont=="BP", ])[1]<10)
                                              1:dim(goDT$down[goDT$down$Ont=="BP", ])[1] else c(1:10) )}
      
      if(is.null(bpnrall)){bpnrall <- ( if (dim(goDT$all[goDT$all$Ont=="BP", ])[1]<10)
                                            1:dim(goDT$all[goDT$all$Ont=="BP", ])[1] else c(1:10)) }
      if(is.null(mfnrall)){mfnrall <- ( if (dim(goDT$all[goDT$all$Ont=="MF", ])[1]<10)
                                            1:dim(goDT$all[goDT$all$Ont=="MF", ])[1] else c(1:10)) }
      if(is.null(ccnrall)){ccnrall <- ( if (dim(goDT$all[goDT$all$Ont=="CC", ])[1]<10)
                                            1:dim(goDT$all[goDT$all$Ont=="CC", ])[1] else c(1:10))}
      
      if(is.null(variablepca)){variablepca=NULL}
      if(is.null(samplecluster)){samplecluster=NULL}
      params <- list(nrup=nrup, nrdown=nrdown, bpnrup=bpnrup, bpnrdown=bpnrdown,
                     mfnrup=mfnrup, mfnrdown=mfnrdown, ccnrup=ccnrup, ccnrdown=ccnrdown,
                     variablepca=variablepca, samplecluster=samplecluster, tempdir =tempdir(),
                     gseanr=gseanr, author=author(), gene = gene(), numheatmap=numheatmap(), nrall = nrall,
                     bpnrall=bpnrall, mfnrall=mfnrall, ccnrall=ccnrall,
                     explainPreview=explainPreview(), biologicalText=biologicalText(),
                     keggAllText = keggAllText(), GSEAText = GSEAText(), deseq = datos$dds, 
                     kggAll = kgg$all, kggUp = kgg$up, kggDown = kgg$down,
                     kggDTall = kggDT$all, kggDTup = kggDT$up, kggDTdown = kggDT$down,
                     goAll = go$all, goDTall = goDT$all, goUp=go$up, goDTup = goDT$up,
                     goDown = go$down, goDTdown = goDT$down, gsea = gsea$gsea)
      rmarkdown::render(
        tempReport,
        output_file = file,
        params = params,
        envir = new.env(parent = globalenv( ))
      )
    } )
  # output$reportpdf <- downloadHandler(
  #   # For PDF output, change this to "report.pdf"
  #   filename = "report.pdf",
  #   content = function(file) {
  #     tempReport <- file.path(tempdir(), "pdfReport.Rmd")
  #     file.copy("pdfReport.Rmd", tempReport, overwrite = TRUE)
  #     file.copy("utils.R", file.path(tempdir(),"utils.R"), overwrite = TRUE)
  #     file.copy("tmpResources/", tempdir(), overwrite = TRUE, recursive = TRUE)
  #     do.call(file.remove, list(list.files("tmpResources/", full.names = TRUE)))
  #     nrall <- rowsAll()
  #     nrup <- rowsUp()
  #     nrdown <- rowsdown()
  #     if(is.null(nrall)){nrall <- c(1:10)}
  #     if(is.null(nrup)){nrup <- c(1:10)}
  #     if(is.null(nrdown)){nrdown <- c(1:10)}
  #     bpnrall <- bprowsall()
  #     mfnrall <- mfrowsall()
  #     ccnrall <- ccrowsall()
  #     if(is.null(bpnrall)){bpnrall <- c(1:10)}
  #     if(is.null(mfnrall)){mfnrall <- c(1:10)}
  #     if(is.null(ccnrall)){ccnrall <- c(1:10)}
  #     bpnrup <- bprowsup()
  #     mfnrup <- mfrowsup()
  #     ccnrup <- ccrowsup()
  #     if(is.null(bpnrup)){bpnrup <- c(1:10)}
  #     if(is.null(mfnrup)){mfnrup <- c(1:10)}
  #     if(is.null(ccnrup)){ccnrup <- c(1:10)}
  #     bpnrdown <- bprowsdown()
  #     mfnrdown <- mfrowsdown()
  #     ccnrdown <- ccrowsdown()
  #     if(is.null(bpnrdown)){bpnrdown <- c(1:10)}
  #     if(is.null(mfnrdown)){mfnrdown <- c(1:10)}
  #     if(is.null(ccnrdown)){ccnrdown <- c(1:10)}
  #     variablepca <- variables()
  #     if(is.null(variablepca)){variablepca=NULL}
  #     gseanr <- gsearow()
  #     if(is.null(gseanr)){gseanr <- c(1)}
  #     params <- list(nrup=nrup, nrdown=nrdown, bpnrup=bpnrup, bpnrdown=bpnrdown,
  #                    mfnrup=mfnrup, mfnrdown=mfnrdown, ccnrup=ccnrup, ccnrdown=ccnrdown,
  #                    variablepca=variablepca, tempdir =tempdir(),
  #                    gseanr=gseanr, author=author(), nrall = nrall,
  #                    bpnrall=bpnrall, mfnrall=mfnrall, ccnrall=ccnrall)
  #     rmarkdown::render(
  #       tempReport,
  #       output_file = file,
  #       params = params,
  #       envir = new.env(parent = globalenv())
  #     )
  #   } )
}


shinyApp(ui, server)