---
title: "Enrichment background"
date: "2020"
output: 
  rmdformats::readthedown:
    highlight: kate
editor_options: 
  chunk_output_type: console
---

```{r libraries, include=FALSE, message = FALSE, cache=FALSE}

library("DESeq2")
library("limma")
library("tidyverse")
library("org.Mm.eg.db")
library("EnsDb.Mmusculus.v79")
library("DT")

library('knitr')
library('rmdformats')

```

```{r setup, include=FALSE, message = FALSE, echo=FALSE, cache=FALSE}

options(max.print="75")
knitr::opts_chunk$set(echo=TRUE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)

```

```{r eval=FALSE, include=FALSE}
1. include = FALSE prevents code and results from appearing in the finished file. R Markdown still runs the code in the chunk, and the results can be used by other chunks.
2. echo = FALSE prevents code, but not the results from appearing in the finished file. This is a useful way to embed figures.
3. message = FALSE prevents messages that are generated by code from appearing in the finished file.
4. warning = FALSE prevents warnings that are generated by code from appearing in the finished.
5. fig.cap = "..." adds a caption to graphical results.
6. eval=FALSE the code is shown but not run.
```




```{r, include=FALSE, message = FALSE, cache=FALSE}

#setwd("/media/miriam/Maxtor/aaParis/aaSideProyect/Exploratory-DE/")
#csvfile <- ("/media/miriam/Maxtor/aaParis/aaSideProyect/sample_tableTODAS.csv")
setwd("/datos/repos/enrichapp")
sampleTable <- readRDS("sampleTable.RDS")

######################## Generate DE object with selected genes ################################

featureCounts <- readRDS( "featureCounts.RDS")
 

dds_fc <- DESeqDataSetFromMatrix(countData = featureCounts, colData = DataFrame(sampleTable), design = ~ AAV); dds_fc

keepM10 <- rowMedians(counts(dds_fc[,c(1,2,3,4,5,6,7)])) >= 10 | rowMedians(counts(dds_fc[,c(8,9,10,11,12)])) >= 10 # GFP and/or SOCS3
dds_fc_median10 <- dds_fc[keepM10,]; nrow(dds_fc_median10)

dds_fc_median10$AAV <- relevel(dds_fc_median10$AAV, ref = "GFP")

deseq <- DESeq(dds_fc_median10)

res <- results(deseq)
res_Shrink <- lfcShrink(deseq, coef=2, type="apeglm", res = res)

selected <- which(res_Shrink$padj < .05 & abs(res_Shrink$log2FoldChange) > 0.5 )
DE <- res_Shrink[selected,]

######################## Prepare list of genes (DE and Universe) ################################

universe <- rownames(dds_fc_median10)
de <- rownames(DE)

universe_entrez1 <-  mapIds(org.Mm.eg.db, keys=universe, column="ENTREZID",keytype="ENSEMBL")
universe_entrez2 <-  mapIds(EnsDb.Mmusculus.v79, keys=universe, column="ENTREZID",keytype="GENEID")
universe_consensus <- data.frame('Entrez'= ifelse(!is.na(universe_entrez1), as.vector(universe_entrez1),
              ifelse(!is.na(universe_entrez2),as.vector(universe_entrez2), "NA")), stringsAsFactors = F)
              
de_entrez1 <-  mapIds(org.Mm.eg.db, keys=de, column="ENTREZID",keytype="ENSEMBL")
de_entrez2 <-  mapIds(EnsDb.Mmusculus.v79, keys=de, column="ENTREZID",keytype="GENEID")
de_consensus <- data.frame('Entrez'= ifelse(!is.na(de_entrez1), as.vector(de_entrez1),
              ifelse(!is.na(de_entrez2),as.vector(de_entrez2),"NA")), stringsAsFactors = F)


######################## Prepare object with GO terms and KEGG ################################


# KEGG with custom universe
KEGG <- kegga(de_consensus$Entrez, universe = universe_consensus$Entrez, species = "Mm")
keepKEGG <- KEGG[KEGG$P.DE<=0.05,]
keepKEGG$P.DE <- formatC(keepKEGG$P.DE, format = "e", digits = 2)
#kable(head(keepKEGG[order(keepKEGG$DE, decreasing=TRUE), ], 15))

# KEGG with all genes in database
KEGG_All <- kegga(de_consensus$Entrez, universe = NULL, species = "Mm")
keepKEGGALL <- KEGG_All[KEGG_All$P.DE<=0.05,]
keepKEGG$P.DE <- formatC(keepKEGG$P.DE, format = "e", digits = 2)
#kable(head(keepKEGGALL[order(keepKEGGALL$DE, decreasing=TRUE), ], 15))

# GO with custom universe
GO <- goana(de_consensus$Entrez, universe = universe_consensus$Entrez, species = "Mm") 
keepGO <- GO[GO$P.DE<=0.05,]
keepGO$P.DE <- formatC(keepGO$P.DE, format = "e", digits = 2)
#kable(head(keepGO[order(keepGO$DE, decreasing=TRUE), ], 15))
keepGOBP <- keepGO[keepGO$Ont=='BP',]
keepGOBP$P.DE <- formatC(keepGOBP$P.DE, format = "e", digits = 2)
keepGOMF <- keepGO[keepGO$Ont=='MF',]
keepGOMF$P.DE <- formatC(keepGOMF$P.DE, format = "e", digits = 2)
keepGOCC <- keepGO[keepGO$Ont=='CC',]
keepGOCC$P.DE <- formatC(keepGOCC$P.DE, format = "e", digits = 2)

# GO with all genes in database
GO_All<- goana(de_consensus$Entrez, universe = NULL, species = "Mm")
keepGOALL <- GO_All[GO_All$P.DE<=0.05,]
#kable(head(keepGOALL[order(keepGOALL$DE, decreasing=TRUE), ], 15))
keepGOALLBP <- keepGOALL[keepGOALL$Ont=='BP',]
keepGOALLBP$P.DE <- formatC(keepGOALLBP$P.DE, format = "e", digits = 2)
keepGOALLMF <- keepGOALL[keepGOALL$Ont=='MF',]
keepGOALLMF$P.DE <- formatC(keepGOALLMF$P.DE, format = "e", digits = 2)
keepGOALLCC <- keepGOALL[keepGOALL$Ont=='CC',]
keepGOALLCC$P.DE <- formatC(keepGOALLCC$P.DE, format = "e", digits = 2)

```


# KEGG analysis


## With all genes in database

```{r echo=FALSE, results='asis'}

datatable2 <- function(df){
    js <- c("function(row, data) {",
                "if (data[4]>1000 | data[3]<1){",
                "$('td:eq('+(3)+')', row).html(data[4].toExponential(3));",
                "}",
                "}")
    opt <- list(rowCallback = DT::JS(js))
    return(DT::datatable(df, options = opt))
}

```

## With custom universe

```{r echo=FALSE, results='asis'}

datatable(keepKEGG) 

```



# GO terms

## With all genes in database
### BP

```{r echo=FALSE, results='asis'}

datatable(keepGOALLBP) 

```

### MF

```{r echo=FALSE, results='asis'}

datatable(keepGOALLMF) 

```

### CC

```{r echo=FALSE, results='asis'}

datatable(keepGOALLCC)

```


## With custom universe
### BP

```{r echo=FALSE, results='asis'}

datatable(keepGOBP) 

```

### MF

```{r echo=FALSE, results='asis'}

datatable(keepGOMF) 

```

### CC

```{r echo=FALSE, results='asis'}

datatable(keepGOCC) 

```

