fluidPage(
    br(),
    fluidRow(
        column(width = 3,
               box(width = 12,
                   pickerInput(
                       inputId = "specie",
                       label = "1. Select species",
                       choices = list("Human" = "Hs",
                                      "Mouse" = "Mm"),
                       options = list(title = "species"),
                       selected = NULL
                   ), 
                   uiOutput("matrixDeseq"),
                   sidebarMenu(fluidRow(
                       column(width=1,
                              menuItem(uiOutput("circleinfoDO")),
                              menuItem(uiOutput("tooltipDO"))
                              ),
                       column(width=12,
                              menuItem(uiOutput("deseqFile"))
                              ) ) ),
                   uiOutput("design"),
                   sidebarMenu(fluidRow(
                       column(width=1,
                              menuItem(uiOutput("circleinfoCM")),
                              menuItem(uiOutput("tooltipCM"))
                              ),
                       column(width=12,
                              menuItem(uiOutput("countFile")),
                       
                              menuItem(uiOutput("sampleFile")))
                       )),
                   uiOutput("testVariable"),
                   uiOutput("designMatrix")
                   ) # fin box
               ),
        column(width = 9,
                    box(width=12,
                        status = "info",
                        title = h1(strong("Welcome to EnrichApp 2021!") ),
                        h3("Before starting using the app"),
                        p("The program will import either a counting matrix 
                                   with a table of sample information 
                (both in separated excel files) or a DeseqDataSet object, 
                generated by the DESeq function of the", 
                a("DESeq2", href="https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html"),
                "library and compress as a RDS file. 
              Make sure that your objects matched this and enjoy your enrichment analysis ;)"),
              br(),
              h3("Get the app ready to be used!"),
              p("First of all, select the species of your experiment. 
              Then the option to choose between entering your Count matrix / DESeq object  
              containing your data will be unlocked. Make your choice and upload your files. 
              Select your conditions and/or design and when the loading symbol stops moving, 
              you will be moved to the next tab! "),
              br(),
              p("Take advantage of every symbol of info" , icon("info-circle"), "that you might find.
              It can provide you with information that may be useful for 
              the proper functioning of the app."),
              br(),
              h3("How to download the app"),
              p("This app can be found on ",
                a("GitHub.", href = "https://github.com/MiriamRiquelmeP/Full-EnrichApp") ) ),
    ) ),
    fluidRow(
        column(width = 6,
               # box(width = 12, 
               #     title = "Sample table",
                   DTOutput("coldataTable")
               #)
        ),
        column(width = 6,
               # box(width = NULL,
               #     title = "Expression matrix (first 10 rows)",
                   #div(style = 'overflow-x: scroll',
               DT::dataTableOutput("expressionTable")#)
                   #)
        )
    )
)